Example from: https://github.com/aymericdamien/TensorFlow-Examples/blob/master/notebooks/1_Introduction/basic_operations.ipynb

In [1]:
import numpy as np
import tensorflow as tf

C:\Users\plubi\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# Constants.
a = tf.constant(2)
b = tf.constant(3, dtype=tf.float32)
a = tf.cast(a, tf.float32)

In [3]:
print(a,b)

Tensor("Cast:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32)


In [4]:
# Running a computation graph.
with tf.Session() as sess:
  print(sess.run([a,b]))

[2.0, 3.0]


In [23]:
# Running a computation graph.
with tf.Session() as sess:
    print ('a: %i') % sess.run(a), ('b: %i') % sess.run(b)
    print "Addition with constants: %i" % sess.run(a+b)
    print "Multiplication with constants: %i" % sess.run(a*b)

SyntaxError: invalid syntax (<ipython-input-23-a45788f228ee>, line 4)

In [8]:
# Placeholders. Defining a computation graph.
a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)
add = tf.add(a, b)
mul = tf.multiply(a, b)

In [9]:
# Running a computation graph.
with tf.Session() as sess:
    # Run every operation with variable input
    print "Addition with variables: %i" % sess.run(add, feed_dict={a: 2, b: 3})
    print "Multiplication with variables: %i" % sess.run(mul, feed_dict={a: 2, b: 3})

SyntaxError: invalid syntax (<ipython-input-9-3344215d2254>, line 4)

In [10]:
# 3-D tensor `a`
# [[[ 1,  2,  3],
#   [ 4,  5,  6]],
#  [[ 7,  8,  9],
#   [10, 11, 12]]]
a = tf.constant(np.arange(1, 13, dtype=np.int32),
                shape=[2, 2, 3])

In [11]:
# 3-D tensor `b`
# [[[13, 14],
#   [15, 16],
#   [17, 18]],
#  [[19, 20],
#   [21, 22],
#   [23, 24]]]
b = tf.constant(np.arange(13, 25, dtype=np.int32),
                shape=[2, 3, 2])

In [12]:
# `a` * `b`
# [[[ 94, 100],
#   [229, 244]],
#  [[508, 532],
#   [697, 730]]]
c = tf.matmul(a, b)

In [13]:
with tf.Session() as sess:
  print(sess.run(c))

[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]]


In [14]:
sess = tf.InteractiveSession()

In [15]:
# Variables.
W = tf.Variable([.3], dtype=tf.float32)
b = tf.Variable([-.3], dtype=tf.float32)
x = tf.placeholder(tf.float32)
linear_model = W*x + b

In [16]:
# Variables initializer.
init = tf.global_variables_initializer()
sess.run(init)

In [17]:
# Printing results for initial values.
print(sess.run(linear_model, {x: [1, 2, 3, 4]}))

[0.         0.3        0.6        0.90000004]


In [18]:
# Printing loss value.
y = tf.placeholder(tf.float32)
squared_deltas = tf.square(linear_model - y)
loss = tf.reduce_sum(squared_deltas)
print(sess.run(loss, {x: [1, 2, 3, 4], y: [0, -1, -2, -3]}))

23.66


In [19]:
# Assigning values.
fixW = tf.assign(W, [-1.])
fixb = tf.assign(b, [1.])
sess.run([fixW, fixb])
print(sess.run(loss, {x: [1, 2, 3, 4], y: [0, -1, -2, -3]}))

0.0


In [20]:
# Optimizer.
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [21]:
# Training.
sess.run(init) # reset values to incorrect defaults.
for i in range(1000):
  sess.run(train, {x: [1, 2, 3, 4], y: [0, -1, -2, -3]})

print(sess.run([W, b]))

[array([-0.9999969], dtype=float32), array([0.9999908], dtype=float32)]


Tasks:
1. Print the loss value after the training.
2. Print the loss value when providing a modified target value.
3. Re-train the model starting from other initial values for variables. Does it still converge?